### ISSUE TITLE
[FEATURE] Hold mouse button to ping

### ISSUE THREAD

**Issue by mkahvi** [Moerill/fvtt-pointer#8] opened 2020-11-15 11:44 UTC
**Is your feature request related to a problem? Please describe.**
Old habits that don't die.

**Describe the solution you'd like**
The usual hold left mouse button (primary button? I dunno how handedness stuff affects this) to ping that is seen in the Pings module and in Roll20 and bunch of other places.

**Describe alternatives you've considered**
Getting on with my times and adapting to different behaviour. It's hard. Sorry. I also just feel like the hold to ping is so Convenient.

**Comment by Moerill** [comment] 2020-11-15 11:47
Duplicate of https://github.com/Moerill/fvtt-pointer/issues/2

**Closed by Moerill** 2020-11-15 11:47 UTC
Labels: duplicate, enhancement
