### ISSUE TITLE
[FEATURE] Request roll20 type ping (no need to hold down a key to ping)

### ISSUE THREAD

**Issue by Geodragon9** [Moerill/fvtt-pointer#9] opened 2020-11-15 22:03 UTC
Looking for the option to enable an option or an additional ping where I use left click and hold to create the ping instead of holding down the x and the pressing the left mouse button.

**Comment by Moerill** [comment] 2020-11-15 22:04
duplicate of https://github.com/Moerill/fvtt-pointer/issues/2

**Closed by Moerill** 2020-11-15 22:04 UTC
Labels: duplicate, enhancement

**Comment by Geodragon9** [comment] 2020-11-15 22:09
Not quite a duplicate.  They wanted long press option for right click alternative for mac track pad.

Nov 15, 2020 14:04:47 Moerill <notifications@github.com>:
